### ISSUE TITLE
Please update the fathom code in gatsby-config.js

### ISSUE THREAD

**Issue by jpvalery** [youngbeom-shin/Gatsby-test#1]
You're currently sending data to my Fathom instance. Please remove that. 

Also, since the repo is under MIT please credit the original repo. 

Thanks,

**Comment by youngbeom-shin** [comment]
sorry for disturbing you by mistake, it has been removed, and do i need folk this repo again?  how can i credit the original repo?

**Comment by jpvalery** [comment]
All good. You can add a link to the original repo in the readme.md file like `[Based on MontréalPhotoClub](https://github.com/montrealphotoclub/montrealphotoclub.en)`
